name: Render Remotion Video
on:
  workflow_dispatch:
    inputs:
      beats:
        description: 'Beats (JSON array, ex: [0.5,1.2,2.0])'
        required: true
      audio_url:
        description: 'URL du fichier audio'
        required: true
      audio_duration:
        description: 'Durée audio (secondes)'
        required: true

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci
          # Installation explicite des dépendances TypeScript pour résoudre l'erreur tsx
          npm install -D typescript ts-loader @types/react @types/react-dom
          # Installation du navigateur Chrome pour Remotion
          npx @remotion/renderer ensure-browser

      - name: Setup Chrome/Browser
        run: |
          # Installation manuelle du navigateur
          npx remotion browser ensure --log=verbose
          # Alternative si la première commande échoue
          sudo apt-get update
          sudo apt-get install -y chromium-browser
        continue-on-error: false

      - name: Create public directory
        run: mkdir -p public

      - name: Download audio
        run: curl -L "${{ github.event.inputs.audio_url }}" -o public/audio.mp3

      - name: Render video
        run: |
          npx remotion render src/index.tsx MyComp out/video.mp4 \
            --props='{"beats":${{ github.event.inputs.beats }},"audioDuration":"${{ github.event.inputs.audio_duration }}","audioSrc":"audio.mp3"}' \
            --log=verbose \
            --bundle-cache=false
        env:
          NODE_OPTIONS: "--max-old-space-size=4096"

      - name: Upload video artifact
        uses: actions/upload-artifact@v4
        with:
          name: rendered-video
          path: out/video.mp4
